#!/bin/bash
# Setup local OCR models via Ollama for Singular dev/personal use.
# Requires: Ollama installed (https://ollama.com)
#
# Usage: bash scripts/setup-local-ocr.sh

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔══════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Singular — Local OCR Setup          ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════╝${NC}"
echo ""

# Check Ollama is installed
if ! command -v ollama &> /dev/null; then
    echo -e "${YELLOW}⚠ Ollama not found. Install from: https://ollama.com${NC}"
    echo "  Linux:  curl -fsSL https://ollama.com/install.sh | sh"
    echo "  macOS:  brew install ollama"
    exit 1
fi

echo -e "${GREEN}✓${NC} Ollama found: $(ollama --version 2>/dev/null || echo 'version unknown')"
echo ""

# Pull primary OCR model
echo -e "${BLUE}→ Pulling GLM-OCR (0.9B params, ~2GB)...${NC}"
echo "  This is the primary OCR model — fast, accurate, structured output."
ollama pull glm-ocr
echo -e "${GREEN}✓${NC} GLM-OCR ready"
echo ""

# Pull fallback model (optional)
read -p "Install Qwen2.5-VL 3B as fallback? (~3.5GB download) [y/N] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}→ Pulling Qwen2.5-VL 3B...${NC}"
    ollama pull qwen2.5vl:3b
    echo -e "${GREEN}✓${NC} Qwen2.5-VL 3B ready"
    FALLBACK_LINE="OLLAMA_OCR_FALLBACK_MODEL=qwen2.5vl:3b"
else
    echo -e "${YELLOW}→ Skipping Qwen2.5-VL fallback${NC}"
    FALLBACK_LINE="# OLLAMA_OCR_FALLBACK_MODEL=qwen2.5vl:3b"
fi
echo ""

# Create .env.local if it doesn't exist
ENV_FILE=".env.local"
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠ $ENV_FILE already exists. Not overwriting.${NC}"
    echo "  To update, edit manually or delete and re-run this script."
else
    cat > "$ENV_FILE" << EOF
# Singular — Local OCR configuration
# Generated by setup-local-ocr.sh on $(date -Iseconds)

OCR_PROVIDER=local
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_OCR_MODEL=glm-ocr
${FALLBACK_LINE}
OLLAMA_NUM_CTX=16384
EOF
    echo -e "${GREEN}✓${NC} Created $ENV_FILE"
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Setup complete!                     ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""
echo "  Next steps:"
echo "  1. Make sure Ollama is running:  ollama serve"
echo "  2. Test OCR model:              ollama run glm-ocr"
echo "  3. Start Singular:               npm run all"
echo ""
echo "  The pipeline will use GLM-OCR locally (cost: \$0.00)"
echo "  Gemini API is only used for question structuring."
